### ISSUE TITLE
Please cherry-pick valgrind $ORIGIN patch from upstream

### ISSUE THREAD

**Issue by geofft** [CodSpeedHQ/valgrind-codspeed#1]
Hi! Valgrind upstream just recently fixed [bug 396415 "Valgrind is not looking up $ORIGIN rpath of shebang programs"](https://bugs.kde.org/show_bug.cgi?id=396415) with [commit 1fefba79021779d840bbf8cebc43e40c74b40f31](https://sourceware.org/git/?p=valgrind.git;a=commitdiff;h=1fefba79021779d840bbf8cebc43e40c74b40f31). This bug causes the Python installations used by `uv` to not work properly under CodSpeed. Specifically, if you run something like `codspeed run pytest`, `pytest` is a script whose shebang line references the Python installation, and valgrind does not run the Python interpreter properly.

Valgrind seems to release once or twice a year at most; can you please cherry-pick this patch onto your fork and include it in a CodSpeed release so `uv` users can get unblocked before then?

A simple reproducer is to do something like `uv venv; . .venv/bin/activate; uv pip install pytest; codspeed run pytest`, or something like this in GitHub Actions (see [this sample run](https://github.com/geofft/actions-test-202112/actions/runs/13039184914/job/36376851113)):

```yaml
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: astral-sh/setup-uv@v5
with:
python-version: 3.13
- run: uv pip install pytest
- uses: CodSpeedHQ/action@v3
with:
run: pytest
```
